site_name: A2G Measurements Software
theme: 
  icon:
    admonition:
      example: simple/react
      note: simple/python
      abstract: simple/html5
      info: simple/css3
      tip: simple/javascript
      quote: simple/git
      warning: simple/powershell
      failure: simple/python
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - content.footnote.tooltips
    - content.code.copy
    - content.code.select
    - content.code.annotate
  language: en
  palette:
  # Palette toggle for light mode
    - scheme: default
      primary: indigo
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: lime
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

markdown_extensions:
  - def_list
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
extra:
  annotate:
    json: [.s2]

plugins:
  - search
  - mkdocstrings
  - glightbox
extra_css:
  - stylesheets/extra.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
extra_javascript:
  - javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
nav:
    - Home: index.md
    - Installation: GettingStarted.md
    - Measurement system: 
        - Devices and connections: MeasurementSystem.md
        - Communication between nodes: CommunicationProtocol.md
    - Guide for using the GUI: 
        - Operation of GUI: GuideForGUI.md
        - Panels in GUI: PanelsGUI.md
        - Parameters of GUI: GUIparameters.md
    - Troubleshooting: Troubleshooting.md
    - For developers: InfoDevelopers.md
    - Measurements Planning: 
        - Planning tool: PlanningMeasurements.md
        - Flight plan: FlightPlan.md
    - API reference:
        - DJI Ronin RS2 gimbal: GimbalRS2.md
        - Septentrio GPS: GpsSignaling.md
        - Anritsu Spectrum Analyzer: AnritsuSA.md
        - Nodes communication: NodesCommunication.md
        - Gremsy H16 gimbal: GimbalGremsyH16.md
        - SBUS encoder: SBUSEncoder.md
        - RFSoC communication: RFSoCHandler.md
        - Graphical User Interface - Setup window: GUIsetupWin.md
        - Graphical User Interface - Main window: GUIwidgetGallery.md
        - Utility functions: Utils.md
