# Generated by Django 4.1 on 2022-08-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomaticMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ManualMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_movement', models.CharField(choices=[('abs', 'Absolute'), ('rel', 'Relative')], default='abs', max_length=20)),
                ('yaw', models.IntegerField(default=0, help_text='Enter yaw integer')),
                ('roll', models.IntegerField(default=0, help_text='Enter roll integer')),
                ('pitch', models.IntegerField(default=0, help_text='Enter pitch integer')),
                ('time_tag', models.DateTimeField(verbose_name='Time tag')),
            ],
        ),
        migrations.CreateModel(
            name='PcanInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Presets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
